packageExtensions:
  "@material-ui/types@*":
    peerDependencies:
      react: "*"
  "@types/copy-webpack-plugin@*":
    peerDependencies:
      webpack: "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  "@types/html-webpack-plugin@*":
    peerDependencies:
      webpack: "*"
  "@types/loadable__component@*":
    peerDependencies:
      react: "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/react-redux@*":
    peerDependencies:
      react: "*"
  "@types/react-router-config@*":
    peerDependencies:
      react: "*"
      react-router: "*"
  "@types/react-router-dom@*":
    peerDependencies:
      react: "*"
      react-router: "*"
  "@types/react-router@*":
    dependencies:
      react: "*"
  "@types/react-transition-group@*":
    peerDependencies:
      react: "*"
  "@types/styled-components@*":
    peerDependencies:
      react: "*"
  "@types/terser-webpack-plugin@*":
    peerDependencies:
      webpack: "*"
  "@types/webpack-dev-server@*":
    peerDependencies:
      webpack: "*"
  redux-dynamic-middlewares@*:
    peerDependencies:
      redux: "*"
  redux-dynamic-modules-react@*:
    dependencies:
      "@types/react": "*"
  redux-thunk@*:
    peerDependencies:
      redux: "*"
  webpack-cli@*:
    peerDependencies:
      ts-node: "*"
  webpack-merge@*:
    peerDependencies:
      "@types/webpack": "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
